include: lint_rules.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

  errors:
    included_file_warning: ignore
    missing_required_param: error
    missing_return: warning
    todo: ignore
    sdk_version_async_exported_from_core: ignore
    implicit_dynamic_type: ignore
    invalid_assignment: ignore
    implicit_dynamic_map_literal: ignore
    always_put_control_body_on_new_line: ignore
    dead_code: info

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/injection.config.dart"


